### ISSUE TITLE
feat: Implement unimplemented Timefold Solver API

### ISSUE THREAD

**Issue by Christopher-Chianelli** [TimefoldAI/timefold-solver#971]
- [x] Nearby Selection
- [x] Problem Change
- [ ] TimefoldAI/timefold-solver#966
- [ ] TimefoldAI/timefold-solver#965
- [ ] TimefoldAI/timefold-solver#964
- [ ] Custom Moves
- [ ] Custom Move Selector
- [ ] Custom Entity Selector
- [ ] Custom Value Selector
- [ ] Partitioned Search
- [ ] Custom Termination
- [ ] Constraint Match Aware Incremental Score Calculator
- [ ] Custom Acceptor

We don't want Benchmarker in Python.

**Comment by triceo** [comment]
As of today, Timefold halted any further development of the Python solver. 
Find out more here: https://github.com/TimefoldAI/timefold-solver/discussions/1698

Closing this issue.
